language: node_js
node_js:
  - "lts/*"
cache:
  - yarn
  - npm
os:
  - linux
  - osx
branches:
  only:
    - master
    - stable
    - staging
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
jobs:
  include:
    - stage: tests
      name: "Integration tests"
      before_script:
        - yarn build
      script:
        - yarn test
